import math

def fill_ellipse(grid, center_x, center_y, rx, ry, char_fill, char_outline=None):
    if char_outline is None:
        char_outline = char_fill
    for y in range(48):
        for x in range(48):
            dx = x - center_x
            dy = y - center_y
            val = (dx*dx)/(rx*rx) + (dy*dy)/(ry*ry) if rx > 0 and ry > 0 else 2
            if val <= 1:
                # Add outline if it's on the edge
                if char_outline != char_fill and getattr(fill_ellipse, 'outline_active', True):
                    # check neighbors to draw outline
                    is_edge = False
                    for nx, ny in [(x-1,y), (x+1,y), (x,y-1), (x,y+1)]:
                        ndx = nx - center_x
                        ndy = ny - center_y
                        n_val = (ndx*ndx)/(rx*rx) + (ndy*ndy)/(ry*ry)
                        if n_val > 1:
                            is_edge = True
                            break
                    grid[y][x] = char_outline if is_edge else char_fill
                else:
                    grid[y][x] = char_fill

def generate_flower(stage):
    grid = [['.' for _ in range(48)] for _ in range(48)]
    
    # Stem (L: leaf/green, D: outline)
    for y in range(24, 46):
        grid[y][23] = 'D'
        grid[y][24] = 'D'
        if y < 45:
            grid[y][23] = 'L'
            
    # Base Leaves
    fill_ellipse(grid, 20, 36, 6, 2, 'L', 'D')
    fill_ellipse(grid, 28, 38, 5, 2, 'L', 'D')
    
    center_x, center_y = 24, 24
    
    if stage == 'bud':
        # mostly closed green leaves wrapping a tiny brown bud
        center_y = 26
        fill_ellipse(grid, center_x, center_y, 5, 5, 'L', 'D')
        fill_ellipse(grid, center_x, center_y - 2, 3, 3, 'C', 'D')
    elif stage == 'opening':
        center_y = 25
        fill_ellipse(grid, center_x, center_y + 1, 6, 4, 'L', 'D')
        fill_ellipse(grid, center_x, center_y - 3, 4, 3, 'F', 'D')
        fill_ellipse(grid, center_x, center_y - 1, 5, 4, 'C', 'D')
    elif stage == 'early_petals':
        center_y = 24
        fill_ellipse(grid, center_x, center_y + 2, 6, 3, 'L', 'D')
        fill_ellipse(grid, center_x, center_y, 7, 6, 'F', 'D')
        fill_ellipse(grid, center_x, center_y + 1, 6, 5, 'C', 'D')
    elif stage == 'half_bloom':
        center_y = 22
        fill_ellipse(grid, center_x, center_y, 10, 8, 'F', 'D')
        fill_ellipse(grid, center_x, center_y + 1, 8, 6, 'C', 'D')
    elif stage == 'mostly_open':
        center_y = 20
        fill_ellipse(grid, center_x, center_y, 12, 10, 'F', 'D')
        fill_ellipse(grid, center_x, center_y + 1, 9, 8, 'C', 'D')
    elif stage == 'open_flower':
        center_y = 18
        # Petals
        for angle in range(0, 360, 45):
            rad = math.radians(angle)
            px = int(center_x + math.cos(rad) * 11)
            py = int(center_y + math.sin(rad) * 11)
            fill_ellipse(grid, px, py, 4, 4, 'F', 'D')
        fill_ellipse(grid, center_x, center_y, 11, 11, 'C', 'D')
    elif stage == 'full_bloom':
        center_y = 16
        # Lots of petals
        for angle in range(0, 360, 30):
            rad = math.radians(angle)
            px = int(center_x + math.cos(rad) * 12)
            py = int(center_y + math.sin(rad) * 12)
            fill_ellipse(grid, px, py, 5, 5, 'F', 'D')
        fill_ellipse(grid, center_x, center_y, 12, 12, 'C', 'D')
    elif stage == 'full_bloom_celebration':
        center_y = 16
        # Same as full bloom but sparkles
        for angle in range(0, 360, 30):
            rad = math.radians(angle)
            px = int(center_x + math.cos(rad) * 12)
            py = int(center_y + math.sin(rad) * 12)
            fill_ellipse(grid, px, py, 5, 5, 'F', 'D')
        fill_ellipse(grid, center_x, center_y, 12, 12, 'C', 'D')
        # add sparkles
        grid[4][10] = 'W'
        grid[5][10] = 'W'
        grid[10][38] = 'W'
        grid[11][38] = 'W'
        grid[24][8] = 'W'

    # Outline pass cleanup, just make sure we flatten to string
    res = []
    for row in grid:
        res.append("".join(row))
    return res

stages = [
    'bud', 'opening', 'early_petals', 'half_bloom', 
    'mostly_open', 'open_flower', 'full_bloom', 'full_bloom_celebration'
]

print("// AUTO-GENERATED BY SUNFLOWER_GEN.PY")
print("part of 'mitra_sunflower.dart';\n")

for st in stages:
    data = generate_flower(st)
    print(f"const List<String> _{st} = [")
    for r in data:
        print(f"  '{r}',")
    print("];\n")
