# Gen script for explicit pixel-art frames
# Mappings:
# D: Deep Plum/Brown (Outline)
# I: Warm Ivory/Cream (Body)
# P: Soft Peach (Ears)
# A: Peach (Cheeks)
# K: Black (Eyes)
# W: White (Eye sparkles)

def str_to_frame(s):
    # Trims empty lines and removes spaces
    lines = [L for L in s.split('\n') if L.strip()]
    return "'" + "'.replaceAll(' ', '').split('') + \n'".join(lines) + "'.replaceAll(' ', '').split('')"
    
idle = """
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
.............DDDDDDD............................
..........DDDPPPPPPPPDD.........................
.........DDPPPPPPPPPPPPD........DDDDDD..........
........DDPPPPPPPPPPPPPPD.....DDIIIIIIDD........
.......DDPPPPPPPPPPPPPPPPD...DIIIIIIIIIID.......
......DDPPPPPPPPPPPPPPPPPPD.DIIIIIIIIIIIID......
......DDPPPPPPPPPPPPPPPPPPDDIIIIIIIIIIIIIID.....
......DDPPPPPPPPPPPPPPPPPPDIIIIAAIIIAIIIIID.....
......DDPPPPPPPPPPPPPPPPPPDIIIIKKIIWIIIIIID.....
.......DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIIIIID.....
.......DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIIIID......
........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIID.......
.........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIDD........
..........DDPPPPPPPPPPPPPPPPPPDDIIIIIDD.........
...........DDPPPPPPPPPPPPPPPPPPDIIIIIDD.........
.............DDDDDDDDDDDPPPPPPDDIIIIIDD.........
.................DDDDDIIIIIIIIIDIIIIIDD.........
......DD..........DDIIIIIIIIIIIDDIIIIIDD........
.......DD.........DDIIIIIIIIIIIDDIIIIIDD........
.......D..........DDIIIIIIIIIIIDDIIIIDDD........
..................DDIIIIIIIIIIIIDIIIDDD.........
..................DDIIIIIIIIIIIIIIDDD...........
..................DDIIIIIIIIIIIIIIIIIDD.........
...................DDIIIIIIIIIIIIIIIIID.........
...................DDIIIIIDD.DDIIIIIIID.........
...................DDIIIIID...DDIIIIIID.........
...................DDIIIIID...DDIIIIIID.........
..................DDDIIIIID...DDDIIIIID.........
..................DDDIIIIID...DDDIIIIID.........
..................DDDDIIIID...DDDDIIIID.........
...................DDDDDDDD....DDDDDDDD.........
................................................
................................................
................................................
................................................
................................................
................................................
................................................
"""

blink = idle.replace("KK", "DD").replace("W", "D") # simple eye close

walk1 = idle.replace("DDDDIIIID...DDDDIIIID", "DDDIIIIID.....DDDDIIID")
walk2 = idle

sniff = """
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
.............DDDDDDD............................
..........DDDPPPPPPPPDD.........................
.........DDPPPPPPPPPPPPD........DDDDDD..........
........DDPPPPPPPPPPPPPPD.....DDIIIIIIDD........
.......DDPPPPPPPPPPPPPPPPD...DIIIIIIIIIID.......
......DDPPPPPPPPPPPPPPPPPPD.DIIIIIIIIIIIID......
......DDPPPPPPPPPPPPPPPPPPDDIIIIIIIIIIIIIID.....
......DDPPPPPPPPPPPPPPPPPPDIIIIAAIIIAIIIIID.....
......DDPPPPPPPPPPPPPPPPPPDIIIIKKIIWIIIIIID.....
.......DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIIIIID.....
.......DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIIIID......
........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIID.......
.........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIDD........
..........DDPPPPPPPPPPPPPPPPPPDDIIIIIDDDDD......
...........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIDD....
.............DDDDDDDDDDDPPPPPPDDIIIIIIIIIIIDD...
.................DDDDDIIIIIIIIIDIIIIIIIIIIDD....
......DD..........DDIIIIIIIIIIIDDDDDDDDDDDD.....
.......DD.........DDIIIIIIIIIIIDD...............
.......D..........DDIIIIIIIIIIIDD...............
..................DDIIIIIIIIIIIID...............
..................DDIIIIIIIIIIIIIIDDD...........
..................DDIIIIIIIIIIIIIIIIIDD.........
...................DDIIIIIIIIIIIIIIIIID.........
...................DDIIIIIDD.DDIIIIIIID.........
...................DDIIIIID...DDIIIIIID.........
...................DDIIIIID...DDIIIIIID.........
..................DDDIIIIID...DDDIIIIID.........
..................DDDIIIIID...DDDIIIIID.........
..................DDDDIIIID...DDDDIIIID.........
...................DDDDDDDD....DDDDDDDD.........
................................................
................................................
................................................
................................................
................................................
................................................
................................................
"""

# Lift: Trunk curling highly up and holding something
lift = """
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
.............DDDDDDD............................
..........DDDPPPPPPPPDD.........................
.........DDPPPPPPPPPPPPD........DDDDDD..DD......
........DDPPPPPPPPPPPPPPD.....DDIIIIIIDD.DD.....
.......DDPPPPPPPPPPPPPPPPD...DIIIIIIIIIIIDD.....
......DDPPPPPPPPPPPPPPPPPPD.DIIIIIIIIIIIID......
......DDPPPPPPPPPPPPPPPPPPDDIIIIIIIIIIIIID......
......DDPPPPPPPPPPPPPPPPPPDIIIIAAIIIAIIIID......
......DDPPPPPPPPPPPPPPPPPPDIIIIKKIIWIIIIID......
.......DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIIIID......
.......DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIIID.......
........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIID........
.........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIDD........
..........DDPPPPPPPPPPPPPPPPPPDDIIIIIDD.........
...........DDPPPPPPPPPPPPPPPPPPDIIIIIDD.........
.............DDDDDDDDDDDPPPPPPDDIIIIIDD.........
.................DDDDDIIIIIIIIIDIIIIIDD.........
......DD..........DDIIIIIIIIIIIDDIIIIIDD........
.......DD.........DDIIIIIIIIIIIDDIIIIIDD........
.......D..........DDIIIIIIIIIIIDDIIIIDDD........
..................DDIIIIIIIIIIIIDIIIDDD.........
..................DDIIIIIIIIIIIIIIDDD...........
..................DDIIIIIIIIIIIIIIIIIDD.........
...................DDIIIIIIIIIIIIIIIIID.........
...................DDIIIIIDD.DDIIIIIIID.........
...................DDIIIIID...DDIIIIIID.........
...................DDIIIIID...DDIIIIIID.........
..................DDDIIIIID...DDDIIIIID.........
..................DDDIIIIID...DDDIIIIID.........
..................DDDDIIIID...DDDDIIIID.........
...................DDDDDDDD....DDDDDDDD.........
................................................
................................................
................................................
................................................
................................................
................................................
................................................
"""

# Sit: Legs pointed forward horizontally
sit = """
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
.............DDDDDDD............................
..........DDDPPPPPPPPDD.........................
.........DDPPPPPPPPPPPPD........DDDDDD..........
........DDPPPPPPPPPPPPPPD.....DDIIIIIIDD........
.......DDPPPPPPPPPPPPPPPPD...DIIIIIIIIIID.......
......DDPPPPPPPPPPPPPPPPPPD.DIIIIIIIIIIIID......
......DDPPPPPPPPPPPPPPPPPPDDIIIIIIIIIIIIIID.....
......DDPPPPPPPPPPPPPPPPPPDIIIIAAIIIAIIIIID.....
......DDPPPPPPPPPPPPPPPPPPDIIIIKKIIWIIIIIID.....
.......DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIIIIID.....
.......DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIIIID......
........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIIIID.......
.........DDPPPPPPPPPPPPPPPPPPDIIIIIIIIDD........
..........DDPPPPPPPPPPPPPPPPPPDDIIIIIDD.........
...........DDPPPPPPPPPPPPPPPPPPDIIIIIDD.........
.............DDDDDDDDDDDPPPPPPDDIIIIIDD.........
.................DDDDDIIIIIIIIIDIIIIIDD.........
..................DDIIIIIIIIIIIDDIIIIIDD........
..................DDIIIIIIIIIIIDDIIIIIDD........
..................DDIIIIIIIIIIIDDIIIIDDD........
..................DDIIIIIIIIIIIIDIIIDDD.........
..................DDIIIIIIIIIIIIIIIDDDD.........
......DDD.........DDIIIIIIIIIIIIIIIIIDD.........
......DDIIIDDDD....DDIIIIIIIIIIIIIIIIID.........
.......DDIIIIIIIDDDDIIIIIDD.DDIIIIIIIIIDDD......
........DDDDDDDDDDDIIIIIID...DDIIIIIIIIIIID.....
...................DDIIIIIID..DDIIIIIIIIIIID....
..................DDDIIIIIID...DDDIIIIIIIID.....
..................DDDIIIIIID...DDDIIIIIIID......
..................DDDDDDDDDD...DDDDDDDDDD.......
................................................
................................................
................................................
................................................
................................................
................................................
"""


# Prepare export mapping
frame_exports = {
    'idle': idle,
    'blink': blink,
    'walk1': walk1,
    'walk2': walk2,
    'sniff': sniff,
    'hug': sniff,  # Reusing for now
    'lift': lift,
    'spin': idle,  # Will horizontally flip in Flutter? No, just use idle
    'play': sniff,
    'sit': sit,
    'celebration': lift,
}

# The user originally requested multiple exact states:
# IDLE, BLINK, WALK, CURIOUS, HAPPY, EXCITED, PROUD, SLEEPY, ENCOURAGE, FLOWER_INSPECTION, FLOWER_HUG, FLOWER_LIFT, FLOWER_SPIN, FLOWER_PLAY, SITTING_TOGETHER, FLOWER_CELEBRATION
# To make absolutely sure they are available, duplicate into these names
dart_states = {
    'idle1': idle, 'idle2': idle, 'blink': blink,
    'walk1': walk1, 'walk2': walk2, 'walk3': walk1, 'walk4': walk2,
    'curious': sniff,
    'happy1': idle, 'happy2': idle,
    'excited1': lift, 'excited2': lift,
    'proud': sit,
    'sleepy1': sit, 'sleepy2': sit, 'sleep1': sit, 'sleep2': sit,
    'encourage1': lift, 'encourage2': lift,
    'flower_inspection': sniff, 'flower_hug': sniff,
    'flower_lift': lift, 'flower_spin': idle, 'flower_play': sniff,
    'sitting_together': sit, 'flower_celebration': lift,
    'tired1': sit, 'tired2': sit,
    'greeting1': sniff, 'greeting2': sniff,
    'eat1': sniff, 'eat2': sniff,
    'drink1': sniff, 'drink2': sniff,
    'workout1': sit, 'workout2': sit,
    'celebrating1': lift, 'celebrating2': lift,
}

out = '''// ignore_for_file: unused_element
part of 'mitra_sprite.dart';
// GENERATED PIXEL ART FRAMES 48x48

List<String> _parseFrame(String raw) => raw.split('');

'''

for k, v in dart_states.items():
    out += f'final _{k} = {str_to_frame(v)};\n\n'

with open("c:/Users/sande/OneDrive/Desktop/trufit-another/trufit-bodamma-another-copy/lib/widgets/gen_frames_48.dart", "w", encoding='utf-8') as f:
    f.write(out)

print("Frames generated successfully!")
