import os

idle_base = """
................................................
................................................
................................................
................................................
................................................
.............................DDDDDDD............
...........................DDIIIIIIIDD..........
..........................DIIIIIIIIIIID.........
.........................DIIIIIIIIIIIIID........
...................DDDD..DIIIIIIIIIIIIIIID......
.................DDPPPPDDDIIIIAAIIIAIIIIIID.....
...............DDPPPPPPPPDIIIIKKIIWIIIIIIID.....
..............DPPPPPPPPPPPIDIIIIIIIIIIIIIIID....
.......DDDD...DPPPPPPPPPPPIDIIIIIIIIIIIIIDDD....
.....DDIIIIID.DPPPPPPPPPPPIDIIIIIIIIIDDDD.......
....DIIIIIIIIDDPPPPPPPPPPPPIDIIIIIIID...........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIID..........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIIID...DD....
..DIIIIIIIIIIIIDPPPPPPPPPPPPIDDIIIIIIID.DDIIID..
..DIIIIIIIIIIIIIDPPPPPPPPPPPDD.DIIIIIIIDIIIIIID.
...DIIIIIIIIIIIIDDPPPPPPPPPDD..DIIIIIIIIIIIIIID.
...DIIIIIIIIIIIIIDDPPPPPPDD.....DIIIIIIIIIIIID..
...DIIIIIIIIIIIIIIDDDDDDDD.......DIIIIIIIIIDD...
...DIIIIIIIIIIIIDD.................DDDDDDDD.....
...DIIIIIIIIIIDD...DIIIIIID.....................
...DIIIIIIIIIDD....DIIIIIIID....................
...DIIIIIIIIID......DIIIIIIID...................
...DIIIIIIIIID......DIIIIIIID...................
...DIIIIIIIIID......DIIIIIIIID..................
..DIIIIIIIIID......DIIIIIIIIIID.................
..DIIIIIIIIID.....DIIIIIIIIIIID.................
..DIIIIIIIIID.....DIIIIIIIIIDDD.................
..DDDDDDDDDDD.....DDDDDDDDDD....................
................................................
................................................
................................................
"""

# Helper to normalize multiline strings into list of lines
def get_lines(s):
    return [l for l in s.split('\n') if l.strip()]

idle_lines = get_lines(idle_base)

def build_frame(modifier_func):
    new_lines = []
    for y, line in enumerate(idle_lines):
        new_lines.append(modifier_func(y, line))
    return "\n".join(new_lines)

# Blink: replace K with D, W with I
def blink_mod(y, line):
    if 'K' in line:
        return line.replace('KK', 'DD').replace('W', 'D')
    return line

blink = build_frame(blink_mod)

# Walk:
def walk1_mod(y, line):
    # Front leg from y=24 to y=32. Indent front leg left by 2.
    if y >= 25 and len(line) > 30:
        # Simplistic approach: manual override of bottom rows
        # The front leg is roughly x=20 to x=28 in string index.
        # Wait, the string is length 48.
        pass
    return line

# Because simple string replacement is hard for shifting specific legs without breaking the outline,
# I will supply explicit overrides for the bottom 8 lines.
walk1 = """
................................................
................................................
................................................
................................................
................................................
.............................DDDDDDD............
...........................DDIIIIIIIDD..........
..........................DIIIIIIIIIIID.........
.........................DIIIIIIIIIIIIID........
...................DDDD..DIIIIIIIIIIIIIIID......
.................DDPPPPDDDIIIIAAIIIAIIIIIID.....
...............DDPPPPPPPPDIIIIKKIIWIIIIIIID.....
..............DPPPPPPPPPPPIDIIIIIIIIIIIIIIID....
.......DDDD...DPPPPPPPPPPPIDIIIIIIIIIIIIIDDD....
.....DDIIIIID.DPPPPPPPPPPPIDIIIIIIIIIDDDD.......
....DIIIIIIIIDDPPPPPPPPPPPPIDIIIIIIID...........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIID..........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIIID...DD....
..DIIIIIIIIIIIIDPPPPPPPPPPPPIDDIIIIIIID.DDIIID..
..DIIIIIIIIIIIIIDPPPPPPPPPPPDD.DIIIIIIIDIIIIIID.
...DIIIIIIIIIIIIDDPPPPPPPPPDD..DIIIIIIIIIIIIIID.
...DIIIIIIIIIIIIIDDPPPPPPDD.....DIIIIIIIIIIIID..
...DIIIIIIIIIIIIIIDDDDDDDD.......DIIIIIIIIIDD...
...DIIIIIIIIIIIIDD.................DDDDDDDD.....
...DIIIIIIIIIIDD.DIIIIIID.......................
...DIIIIIIIIIDD.DIIIIIIID.......................
...DIIIIIIIIID...DIIIIIIID......................
...DIIIIIIIIID...DIIIIIIID......................
...DIIIIIIIIID...DIIIIIIIID.....................
..DIIIIIIIIID...DIIIIIIIIIID....................
..DIIIIIIIIID..DIIIIIIIIIIID....................
..DIIIIIIIIID..DIIIIIIIIIDDD....................
..DDDDDDDDDDD..DDDDDDDDDD.......................
................................................
................................................
................................................
"""

walk3 = """
................................................
................................................
................................................
................................................
................................................
.............................DDDDDDD............
...........................DDIIIIIIIDD..........
..........................DIIIIIIIIIIID.........
.........................DIIIIIIIIIIIIID........
...................DDDD..DIIIIIIIIIIIIIIID......
.................DDPPPPDDDIIIIAAIIIAIIIIIID.....
...............DDPPPPPPPPDIIIIKKIIWIIIIIIID.....
..............DPPPPPPPPPPPIDIIIIIIIIIIIIIIID....
.......DDDD...DPPPPPPPPPPPIDIIIIIIIIIIIIIDDD....
.....DDIIIIID.DPPPPPPPPPPPIDIIIIIIIIIDDDD.......
....DIIIIIIIIDDPPPPPPPPPPPPIDIIIIIIID...........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIID..........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIIID...DD....
..DIIIIIIIIIIIIDPPPPPPPPPPPPIDDIIIIIIID.DDIIID..
..DIIIIIIIIIIIIIDPPPPPPPPPPPDD.DIIIIIIIDIIIIIID.
...DIIIIIIIIIIIIDDPPPPPPPPPDD..DIIIIIIIIIIIIIID.
...DIIIIIIIIIIIIIDDPPPPPPDD.....DIIIIIIIIIIIID..
...DIIIIIIIIIIIIIIDDDDDDDD.......DIIIIIIIIIDD...
...DIIIIIIIIIIIIDD.................DDDDDDDD.....
...DIIIIIIIIIIDD.....DIIIIIID...................
....DIIIIIIIIIDD......DIIIIIIID.................
.....DIIIIIIIIID.......DIIIIIIID................
.....DIIIIIIIIID.......DIIIIIIID................
.....DIIIIIIIIID.......DIIIIIIIID...............
......DIIIIIIIIID.......DIIIIIIIIIID............
......DIIIIIIIIID......DIIIIIIIIIIID............
......DIIIIIIIIID......DIIIIIIIIIDDD............
......DDDDDDDDDDD......DDDDDDDDDD...............
................................................
................................................
................................................
"""

sit = """
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
.............................DDDDDDD............
...........................DDIIIIIIIDD..........
..........................DIIIIIIIIIIID.........
.........................DIIIIIIIIIIIIID........
...................DDDD..DIIIIIIIIIIIIIIID......
.................DDPPPPDDDIIIIAAIIIAIIIIIID.....
...............DDPPPPPPPPDIIIIKKIIWIIIIIIID.....
..............DPPPPPPPPPPPIDIIIIIIIIIIIIIIID....
.......DDDD...DPPPPPPPPPPPIDIIIIIIIIIIIIIDDD....
.....DDIIIIID.DPPPPPPPPPPPIDIIIIIIIIIDDDD.......
....DIIIIIIIIDDPPPPPPPPPPPPIDIIIIIIID...........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIID..........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIIID...DD....
..DIIIIIIIIIIIIDPPPPPPPPPPPPIDDIIIIIIID.DDIIID..
..DIIIIIIIIIIIIIDPPPPPPPPPPPDD.DIIIIIIIDIIIIIID.
...DIIIIIIIIIIIIDDPPPPPPPPPDD..DIIIIIIIIIIIIIID.
...DIIIIIIIIIIIIIDDPPPPPPDD.....DIIIIIIIIIIIID..
.....DIIIIIIIIIIIIIIDDDDDDDD.......DIIIIIIIIIDD.
......DIIIIIIIIIIIID.................DDDDDDDD...
.......DDIIIIIIIIIIDD..DIIIIIID.................
...DDD...DIIIIIIIIIDD...DIIIIIIID...............
..DIIID...DIIIIIIIIID....DIIIIIIID..............
..DIIID...DIIIIIIIIID....DIIIIIIID..............
.DIIIIID..DIIIIIIIIID....DIIIIIIIID.............
.DIIIIIIIDDIIIIIIIIID...DIIIIIIIIIID............
..DIIIIIIIIIIIIIIIIID..DIIIIIIIIIIID............
...DDDDDDDDDDIIIIIIID..DIIIIIIIIIDDD............
.............DDDDDDDD..DDDDDDDDDD...............
"""

sniff = """
................................................
................................................
................................................
................................................
................................................
.............................DDDDDDD............
...........................DDIIIIIIIDD..........
..........................DIIIIIIIIIIID.........
.........................DIIIIIIIIIIIIID........
...................DDDD..DIIIIIIIIIIIIIIID......
.................DDPPPPDDDIIIIAAIIIAIIIIIID.....
...............DDPPPPPPPPDIIIIKKIIWIIIIIIID.....
..............DPPPPPPPPPPPIDIIIIIIIIIIIIIIID....
.......DDDD...DPPPPPPPPPPPIDIIIIIIIIIIIIIDDD....
.....DDIIIIID.DPPPPPPPPPPPIDIIIIIIIIIDDDD.......
....DIIIIIIIIDDPPPPPPPPPPPPIDIIIIIIID...........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIID..........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIIID...DD....
..DIIIIIIIIIIIIDPPPPPPPPPPPPIDDIIIIIIID.DDIIID..
..DIIIIIIIIIIIIIDPPPPPPPPPPPDD.DIIIIIIIDIIIIIID.
...DIIIIIIIIIIIIDDPPPPPPPPPDD..DIIIIIIIIIIIIIID.
...DIIIIIIIIIIIIIDDPPPPPPDD.....DIIIIIIIIIIIID..
...DIIIIIIIIIIIIIIDDDDDDDD.......DIIIIIIIIIDD...
...DIIIIIIIIIIIIDD.................DDDDDDDD.....
...DIIIIIIIIIIDD................................
...DIIIIIIIIIDD.................................
...DIIIIIIIIID.....DDDDDD.......................
...DIIIIIIIIID...DDIIIIIID......................
...DIIIIIIIIID..DIIIIIIIIIDD....................
..DIIIIIIIIID..DIIIIIIIIIIID....................
..DIIIIIIIIID..DIIIIIIIIIIID....................
..DIIIIIIIIID..DDDDIIIIIIIDD....................
..DDDDDDDDDDD......DDDDDDD......................
................................................
................................................
................................................
"""

lift = """
................................................
................................................
................................................
................................................
................................................
.............................DDDDDDD............
...........................DDIIIIIIIDD...DD.....
..........................DIIIIIIIIIIID.D.ID....
.........................DIIIIIIIIIIIIIDD.IID...
...................DDDD..DIIIIIIIIIIIIIIID.IID..
.................DDPPPPDDDIIIIAAIIIAIIIIIIIDIID.
...............DDPPPPPPPPDIIIIKKIIWIIIIIIIIIDID.
..............DPPPPPPPPPPPIDIIIIIIIIIIIIIIIIIDD.
.......DDDD...DPPPPPPPPPPPIDIIIIIIIIIIIIIDDD....
.....DDIIIIID.DPPPPPPPPPPPIDIIIIIIIIIDDDD.......
....DIIIIIIIIDDPPPPPPPPPPPPIDIIIIIIID...........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIID..........
...DIIIIIIIIIIIDPPPPPPPPPPPPIDIIIIIIIID.........
..DIIIIIIIIIIIIDPPPPPPPPPPPPIDDIIIIIIID.........
..DIIIIIIIIIIIIIDPPPPPPPPPPPDD.DIIIIIIID........
...DIIIIIIIIIIIIDDPPPPPPPPPDD..DIIIIIIIIID......
...DIIIIIIIIIIIIIDDPPPPPPDD.....DIIIIIIIIIID....
...DIIIIIIIIIIIIIIDDDDDDDD.......DIIIIIIIIIDD...
...DIIIIIIIIIIIIDD.................DDDDDDDD.....
...DIIIIIIIIIIDD................................
...DIIIIIIIIIDD.................................
...DIIIIIIIIID..................................
...DIIIIIIIIID..................................
...DIIIIIIIIID..................................
..DIIIIIIIIID...................................
..DIIIIIIIIID...................................
..DIIIIIIIIID...................................
..DDDDDDDDDDD...................................
................................................
................................................
................................................
"""

def bob_up(frame_str, offset=2):
    lines = get_lines(frame_str)
    # prepend offset transparent lines
    empty = "." * 48
    bobbed = [empty for _ in range(offset)] + lines[:-offset]
    return "\n".join(bobbed)

celebration = bob_up(lift, 2)

dart_states = {
    'idle': idle_base,
    'blink': blink,
    'walk1': walk1,
    'walk2': idle_base,
    'walk3': walk3,
    'walk4': idle_base,
    'sniff': sniff,
    'hug': sniff,
    'lift': lift,
    'spin': idle_base,
    'play': sniff,
    'sit': sit,
    'celebration': celebration,
    
    # Explicit user list matching exactly:
    'idle1': idle_base, 'idle2': idle_base,
    'curious': sniff,
    'happy1': idle_base, 'happy2': blink,
    'excited1': celebration, 'excited2': lift,
    'proud': sit,
    'sleepy1': sit, 'sleepy2': blink, 'sleep1': sit, 'sleep2': sit, 'tired1': sit, 'tired2': sit,
    'encourage1': lift, 'encourage2': celebration,
    'flower_inspection': sniff, 'flower_hug': sniff,
    'flower_lift': lift, 'flower_spin': idle_base, 'flower_play': sniff,
    'sitting_together': sit, 'flower_celebration': celebration,
    'flower_gentle_push': sniff,
    'greeting1': lift, 'greeting2': idle_base,
    'eat1': sniff, 'eat2': sniff,
    'drink1': sniff, 'drink2': sniff,
    'workout1': celebration, 'workout2': lift,
    'celebrating1': celebration, 'celebrating2': lift,
}


out_dart = '''// ignore_for_file: unused_element
part of 'mitra_sprite.dart';
// GENERATED PIXEL ART FRAMES 48x48

List<String> _parseFrame(String raw) => raw.split('');

def_to_dart = lambda s: "'" + "'.replaceAll(' ', '').split('') + \\n'".join([l for l in s.split('\\n') if l.strip()]) + "'.replaceAll(' ', '').split('')"
'''

def str_to_frame(s):
    lines = [L for L in s.split('\n') if L.strip()]
    return "'" + "'.replaceAll(' ', '').split('') + \n'".join(lines) + "'.replaceAll(' ', '').split('')"

for k, v in dart_states.items():
    out_dart += f'final _{k} = {str_to_frame(v)};\n\n'

with open("c:/Users/sande/OneDrive/Desktop/trufit-another/trufit-bodamma-another-copy/lib/widgets/gen_frames_48.dart", "w", encoding='utf-8') as f:
    f.write(out_dart)

out_kt = """package com.trufit.trufit_bodamma

object MitraFrames {
    // GENERATED 48x48 HANDCRAFTED ELEPHANT SILHOUETTES
"""
for k, v in dart_states.items():
    s = v.replace("\n", "").replace(" ", "")
    out_kt += f'    const val {k.upper()} = "{s}"\n'
out_kt += "}\n"

with open("c:/Users/sande/OneDrive/Desktop/trufit-another/trufit-bodamma-another-copy/android/app/src/main/kotlin/com/trufit/trufit_bodamma/MitraFrames.kt", "w", encoding="utf-8") as f:
    f.write(out_kt)

print("Export Complete")
