import os
from PIL import Image, ImageDraw

def render_sprite(frame_string, filename, scale=1, outline_only=False):
    lines = [line.strip() for line in frame_string.split('\n') if line.strip()]
    if not lines:
        return
        
    width = len(lines[0])
    height = len(lines)
    
    img = Image.new('RGBA', (width * scale, height * scale), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    
    colors = {
        '.': (0, 0, 0, 0),        # Transparent
        'D': (60, 42, 60, 255),   # Deep Plum/Brown (Outline)
        'S': (215, 205, 200, 255),# Muted Taupe Shadow (Body Shadows)
        'E': (230, 190, 180, 255),# Dark Peach/Shadow (Ear Inner Shadows)
        'I': (245, 240, 230, 255),# Warm Ivory/Cream (Body Base)
        'H': (255, 252, 246, 255),# Champagne Highlight 
        'P': (250, 210, 200, 255),# Soft Peach (Ear Base)
        'A': (255, 180, 170, 255),# Sthira Peach (Blush/Accent)
        'K': (20, 20, 20, 255),   # Black (Eyes)
        'W': (255, 255, 255, 255) # White (Eye sparkles)
    }
    
    color_silhouette = {
        k: (40, 40, 40, 255) if k != '.' else (0,0,0,0) for k in colors
    }

    colormap = color_silhouette if outline_only else colors
    
    for y, row in enumerate(lines):
        for x, char in enumerate(row):
            if char in colormap:
                c = colormap[char]
                if c[3] > 0:
                    d.rectangle(
                        [x*scale, y*scale, (x+1)*scale - 1, (y+1)*scale - 1],
                        fill=c
                    )
                    
    img.save(filename)

concept_a_34 = """
................................................
................................................
................................................
................................................
................................................
................................................
....................DDDDDDDD....................
.................DDDHIIIIIHHDD..................
...............DDHHHIIIIIIIIHHD.................
..............DHHHIIIIIIIIIIIIHD................
.............DHIIIIIIIIIIIIIIIIHD...............
........DDDD.DIIIIIIIIIIIIIIIIIIHD.DDDDD........
......DDPPPD.DIIIIIIIIIIIIIIIIIIIDDPPPPEED......
.....DPPPPEEDDIIIIIAAAIIIIIAAAIIIDDPPPEEEED.....
....DPPPPEEEDDIIIIKKKWIIIWKKKIIIDDDPPEEEEED.....
...DPPPPEEEEDDIIIIKKKIIIIIKKKIIIDDPPEEEEEED.....
...DPPPPEEEEDDIIIIIIIIIIIIIIIIIIIDPEEEEEEED.....
..DPPPPEEEEEDDIIIIIIIIIIIIIIIIIIIDPEEEEEEEED....
..DPPPPEEEEEDDDIIIIIIIIIIIIIIIIIIDPEEEEEEEED....
..DPPPPEEEEEDIDIIIIIIIIDDIIIIIIIIIDEEEEEEEED....
..DPPPPEEEEEDIDIIIIIIIDD.DIIIIIIIDDEEEEEEEED....
...DPPPPEEEEDHDIIIIIIIDD.DIIIIIIIDEEEEEEEED.....
...DDPPEEEEDDIHDIIIIIID...DIIIIIIDDEEEEEEDD.....
....DDPPEEDDIHIHDIIIIID...DDIIIIIDDDEEEED.......
......DDDD..DIHHIIIIIID..DDDIIIIID..DDDD........
............DIIIHIIIIID..DIIIIIIID..............
............DDIIHIIIIID.DDIIIIIIID..............
.............DIIHIIIIID.DDIIIIIIID..............
.............DSIHIIIIID..DDIIIIIID..............
.............DSSIIIIIDD...DDIIIIID..............
............DSSSSIIIIDD....DDIIIID..............
............DSSSSIIDDDD.....DDDDD...............
............DSSSSID.............................
...........DSSSSSID.............................
...........DSSDSSID.............................
..........DSSDDSSID.............................
..........DSDDDDSIDD............................
..........DD....DDDD............................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
"""

concept_b_front = """
................................................
................................................
................................................
................................................
................................................
................................................
.....................DDDDDD.....................
..................DDHHIIIIHHDD..................
.................DHHIIIIIIIIHHD.................
................DHIIIIIIIIIIIIHD................
...............DHIIIIIIIIIIIIIIHD...............
......DDDD.....DHIIIIIIIIIIIIIIHD.....DDDD......
....DDPPPPDD...DIIIIIIIIIIIIIIIIID..DDPPPPDD....
...DPPPPEEEED..DIIIAAAIIIIIAAAIIID.DDPPPEEEED...
..DPPPPEEEEED..DDHKKKWIIIIIWKKKHDD.DPEEEEEEEED..
..DPPPEEEEEEED.DDHKKKIIIIIIIKKKHDD.DEEEEEEEEED..
.DPPPEEEEEEEEDDDIHIIIIIIIIIIIIIIHHDDDEEEEEEEEED.
.DPPPEEEEEEEEDIIIIIIIIIDDIIIIIIIIIIDEEEEEEEEED..
.DPPPEEEEEEEEDIIIIIIIIDDDDIHIIIIIIIDEEEEEEEEED..
.DPPPEEEEEEEEDIIIIIIIDD..DDHIIIIIIIDEEEEEEEEED..
..DPPEEEEEEEEDIIIIIIIDD...DDIIIIIIIDEEEEEEEEE...
..DDPPEEEEEEEDDIIIIIIDD...DDIIIIIIDDEEEEEEEDD...
...DDPPEEEEEDDIHIIIIIID...DIIIIIIHDDEEEEEEDD....
.....DDPPEEDDIHHIIIIIID...DIIIIIIHHDDEEEDD......
.......DDDD.DIHHHIIIIIDD.DDIIIIIIHHHDDD.........
............DIIHHIIIIIDDDDDIIIIIIHHID...........
............DIIHHIIIIIDDDDDIIIIIIHHID...........
............DSIHHHIIIIIDDDIIIIIIHIISD...........
............DSSSIHIIIIIIDDIIIIIIIISSD...........
............DSSSSIIIIIIIIDIIIIIIIISSD...........
...........DSSSSSSIIIIIIDDIIIIIIISSSSD..........
...........DSSSSSSSIIIIDD..DIIIIISSSSD..........
..........DSSSSSSSSSIDDD...DDDIIISSSSSD.........
..........DSSSSSDSSSIDD.....DDISSSSDSSD.........
..........DSSSSDDSSSID.......DISSSSDDSD.........
..........DSSDD.DDSSID.......DISSD..DSD.........
..........DSD.....DDSD.......DSDD....DD.........
..........DD.......DDD.......DDD................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
"""

concept_c_sit = """
................................................
................................................
................................................
................................................
................................................
................................................
...................DDDDDDDD.....................
.................DDHIIIIIIHDD...................
................DHIIIIIIIIIIHD..................
...............DHIIIIIIIIIIIIHD.................
..............DHIIIIIIIIIIIIIIHD................
.......DDDDD..DHIIIIIIIIIIIIIIHD..DDDDD.........
.....DDPPPPDD.DHIIIIIIIIIIIIIIHD.DDPPPPD........
....DPPPPEEEEDDIIIIAAIIIIIIAAIIIDDPPPEEEED......
...DPPPPEEEEEDDIIIKKWIIIIIIWKKIIDDPEEEEEED......
...DPPPEEEEEEEDIIIKKIIIIIIIIKKIIDEEEEEEEED......
...DPPPEEEEEEEDIIIIIIIIIIIIIIIIIDEEEEEEEED......
..DPPPEEEEEEEEDHIIIIIIIIDDIIIIIIIDEEEEEEED......
..DPPPEEEEEEEEDHIIIIIIIDDDDHIIIIIDEEEEEEED......
..DPPPEEEEEEEEDDDHIIIIIDD..DHIIIIDEEEEEEED......
..DDPPEEEEEEEDDIIHIIIIIDD..DHIIIIDEEEEEED.......
...DDPPEEEEEDDSIHIIIIIID...DHIIISDDEEEED........
.....DPPEEEDDSIIHIIIIIIDD.DDHIIISDDEEED.........
.......DDD.DDSSIHHIIIIIDDDDDIIIISSDDDD..........
..........DDSSSIHHIIIIIIDDIIIIISSSSD............
.........DDSSSSIHHHIIIIIIIIIIIISSSSDD...........
........DHHHSSSSIIHHIIIIIIIIHIIISSSSHHD.........
.......DIIIIHHSSIIHHHIIIIIIHHIIISSHHIIID........
......DIIIIIIIIHSIIHHHHHHHHHIIIISHIIIIIID.......
.....DIIIIIIIIIHSSIIIIIIIIIIIIISSHIIIIIIID......
.....DIIIIIIIIIIIISSSSSSSSSSSSSSIIIIIIIIID......
....DIIIIIIIIIIIIISSSSSSSSSSSSSSIIIIIIIIIID.....
....DIIIIIIIIIIIIISSSSSSSSSSSSSSIIIIIIIIIID.....
....DIIIIIIIIDDDDDDDSSSSSSSSSSDDDDDDDIIIIID.....
.....DIIIIIDD......DDDDDDDDDDDD......DDIIID.....
......DDDDD............................DDDD.....
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
"""

print("Running Pixel Draft V8...")
if not os.path.exists('renders'):
    os.makedirs('renders')

# Render A
render_sprite(concept_a_34, 'renders/v8_concept_a_48.png', scale=1)
render_sprite(concept_a_34, 'renders/v8_concept_a_80.png', scale=80//48)
render_sprite(concept_a_34, 'renders/v8_concept_a_160.png', scale=160//48)
render_sprite(concept_a_34, 'renders/v8_concept_a_160_sil.png', scale=160//48, outline_only=True)

# Render B
render_sprite(concept_b_front, 'renders/v8_concept_b_48.png', scale=1)
render_sprite(concept_b_front, 'renders/v8_concept_b_80.png', scale=80//48)
render_sprite(concept_b_front, 'renders/v8_concept_b_160.png', scale=160//48)
render_sprite(concept_b_front, 'renders/v8_concept_b_160_sil.png', scale=160//48, outline_only=True)

# Render C
render_sprite(concept_c_sit, 'renders/v8_concept_c_48.png', scale=1)
render_sprite(concept_c_sit, 'renders/v8_concept_c_80.png', scale=80//48)
render_sprite(concept_c_sit, 'renders/v8_concept_c_160.png', scale=160//48)
render_sprite(concept_c_sit, 'renders/v8_concept_c_160_sil.png', scale=160//48, outline_only=True)

print("Done rendering draft V8.")
