import os
from PIL import Image, ImageDraw

def render_sprite(frame_string, filename, scale=1, outline_only=False):
    lines = [line.strip() for line in frame_string.split('\n') if line.strip()]
    if not lines:
        return
        
    width = len(lines[0])
    height = len(lines)
    
    img = Image.new('RGBA', (width * scale, height * scale), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    
    colors = {
        '.': (0, 0, 0, 0),        # Transparent
        'D': (60, 42, 60, 255),   # Deep Plum/Brown (Outline)
        'S': (215, 205, 200, 255),# Muted Taupe Shadow (Body Shadows)
        'E': (230, 190, 180, 255),# Dark Peach/Shadow (Ear Inner Shadows)
        'I': (245, 240, 230, 255),# Warm Ivory/Cream (Body Base)
        'H': (255, 252, 246, 255),# Champagne Highlight 
        'P': (250, 210, 200, 255),# Soft Peach (Ear Base)
        'A': (255, 180, 170, 255),# Sthira Peach (Blush/Accent)
        'K': (20, 20, 20, 255),   # Black (Eyes)
        'W': (255, 255, 255, 255) # White (Eye sparkles)
    }
    
    color_silhouette = {
        k: (40, 40, 40, 255) if k != '.' else (0,0,0,0) for k in colors
    }

    colormap = color_silhouette if outline_only else colors
    
    for y, row in enumerate(lines):
        for x, char in enumerate(row):
            if char in colormap:
                c = colormap[char]
                if c[3] > 0:
                    d.rectangle(
                        [x*scale, y*scale, (x+1)*scale - 1, (y+1)*scale - 1],
                        fill=c
                    )
                    
    img.save(filename)

draft7 = """
................................................
................................................
................................................
................................................
................................................
.............................DDDDDDD............
...........................DDHHHHHHIDD..........
..........................DHHHHIIIIIISD.........
.........................DHIIIIIIIIISSSD........
...................DDDD..DIIIIIIIIIIISSSSD......
.................DDPPPPIDDHIIIAASSIISSSSSD......
...............DDPPPEEPEPDHIIIKWKWIISSSSSD......
..............DPPPPPPEEEPIDIISKKIIISSSSSSSD.....
.......DDDD...DPPPAAPPEEPIDIISIIIIISSSSSDDD.....
.....DDSIIIID.DPAAAAAPEEPIDIIIIIIIISDDDD........
....DHHIIIIISDDPAPPPEEEPPIDIIIIIIISD............
...DHIIIIIIIISDPPPPPEEEPPIDIIIIIIISD............
...DHIIIIIIIISDPPPPPEEEPPIDIIIIIIIISD...DD......
..DHIIIIIIIIISDPPPPPEEEPPIDDIIIIIIISD.DDIIID....
..DIIIIIIIIIISSDPPPPPEEPPDD.DIIIIIIISDIIIIIID...
...DIIIIIIIIIISDDPPPPPEPDD..DSIIIIISSSIIIIIID...
...DSIIIIIIIIIISDDPPPPDD.....DSSSISSSIIIIIID....
...DSSSSSSIIIIIIIIDDDDDD.......DSSSSIIIIIDD.....
...DSDDDDDSSSSSIDD.................DDDDDDDD.....
...DDD...DDISSSIDD...DSHIIIID...................
...........DISSSDD....DSHIIISD..................
...........DSSSSID......DSHIISD.................
...........DSSSSID......DSSIISD.................
...........DSSIIDD......DSSIIDD.................
..........DSSSSID......DSSIIDD..................
..........DSSSSID.....DSSIIDD...................
..........DSDDDDD.....DSDDDDD...................
..........DDDDDDD.....DDDDDDD...................
................................................
................................................
................................................
"""

print("Running Pixel Draft 7...")
if not os.path.exists('renders'):
    os.makedirs('renders')

render_sprite(draft7, 'renders/draft7_idle_48.png', scale=1)
render_sprite(draft7, 'renders/draft7_idle_80.png', scale=80//48)
render_sprite(draft7, 'renders/draft7_idle_160.png', scale=160//48)
render_sprite(draft7, 'renders/draft7_idle_160_sil.png', scale=160//48, outline_only=True)
print("Done rendering draft7.")
