from PIL import Image, ImageDraw

def render_silhouette(_str, size=48, output_path="out.png"):
    s = _str.replace("\n", "").replace(" ", "")
    img = Image.new("RGBA", (48, 48), (255,255,255,255))
    draw = ImageDraw.Draw(img)
    
    for y in range(48):
        for x in range(48):
            char = s[y * 48 + x]
            if char != '.':
                draw.point((x, y), fill=(0,0,0,255))
                
    img.resize((size, size), Image.NEAREST).save(output_path)
    
# Let's completely redraw it with extreme precision.
# 48x48 Grid.
# Head center roughly at X=24, Y=18
# Ear very large on the left, X=8 to 22, Y=10 to 30
# Trunk dropping down on the right, X=32, Y=20 to 38, curving up to X=36
# Legs short, chunky, X=16 and X=26, Y=36 to 44
elephant = """
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
.............OOOOOOO............................
..........OOOOOOOOOOOO..........................
.........OOOOOOOOOOOOOOO........OOOOOO..........
........OOOOOOOOOOOOOOOOO.....OOOOOOOOOO........
.......OOOOOOOOOOOOOOOOOOO...OOOOOOOOOOOO.......
......OOOOOOOOOOOOOOOOOOOOO.OOOOOOOOOOOOOO......
......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.....
......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.....
......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO....
.......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO....
.......OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.....
........OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO......
.........OOOOOOOOOOOOOOOOOOOOOOOOOOOOO.OO.......
..........OOOOOOOOOOOOOOOOOOOOOOOOOOO..OO.......
...........OOOOOOOOOOOOOOOOOOOOOOOOO...OOO......
.............OOOOOOOOOOOOOOOOOOOOOO.....OOO.....
.................OOOOOOOOOOOOOOOOO......OOO.....
......oo..........OOOOOOOOOOOOOOO........OO.....
.......oo.........OOOOOOOOOOOOOOO........OO.....
.......o..........OOOOOOOOOOOOOOO.......OOO.....
..................OOOOOOOOOOOOOOOO......OOO.....
..................OOOOOOOOOOOOOOOOO....OOO......
..................OOOOOOOOOOOOOOOOOOOOOOO.......
...................OOOOOOOOOOOOOOOOOOOOO........
...................OOOOOOOO..OOOOOOOOOO.........
...................OOOOOOO....OOOOOOOO..........
...................OOOOOOO....OOOOOOOO..........
..................OOOOOOOO....OOOOOOOO..........
..................OOOOOOOO....OOOOOOOO..........
..................OOOOOOOO....OOOOOOOO..........
..................OOOOOOOO....OOOOOOOO..........
................................................
................................................
................................................
................................................
................................................
................................................
................................................
"""

import os
art_dir = r"C:\Users\sande\.gemini\antigravity\brain\7d414627-571d-4c75-b3fe-ca0febe97a5b\artifacts"

for y in range(48):
    row = ""
    for x in range(48):
        char = elephant.replace("\n", "").replace(" ", "")[y * 48 + x]
        row += "██" if char != '.' else "  "
    print(row)

render_silhouette(elephant, 160, os.path.join(art_dir, "sil_160.png"))
render_silhouette(elephant, 80, os.path.join(art_dir, "sil_80.png"))
render_silhouette(elephant, 48, os.path.join(art_dir, "sil_48.png"))
