import 'dart:convert';
import 'dart:io';

void main() {
  final List<Map<String, dynamic>> table = [
    // RICE MEALS
    {
      "id": "white_rice",
      "name": "White Rice",
      "aliases": ["annam", "rice", "steamed rice", "cooked rice", "plain rice"],
      "per100g": {"kcal": 130, "protein_g": 2.7, "carbs_g": 28.0, "fat_g": 0.3},
      "defaultPortionG": 150,
      "category": "RICE MEALS",
      "estimated": true,
    },
    {
      "id": "curd_rice",
      "name": "Curd Rice",
      "aliases": ["perugu annam", "yogurt rice", "daddojanam"],
      "per100g": {"kcal": 120, "protein_g": 3.0, "carbs_g": 18.0, "fat_g": 4.0},
      "defaultPortionG": 200,
      "category": "RICE MEALS",
      "estimated": true,
    },
    {
      "id": "lemon_rice",
      "name": "Lemon Rice",
      "aliases": ["nimmakaya pulihora", "chitranna"],
      "per100g": {"kcal": 160, "protein_g": 3.0, "carbs_g": 25.0, "fat_g": 5.0},
      "defaultPortionG": 150,
      "category": "RICE MEALS",
      "estimated": true,
    },
    {
      "id": "tamarind_rice",
      "name": "Tamarind Rice",
      "aliases": ["chintapandu pulihora", "pulihora"],
      "per100g": {"kcal": 160, "protein_g": 3.0, "carbs_g": 26.0, "fat_g": 5.0},
      "defaultPortionG": 150,
      "category": "RICE MEALS",
      "estimated": true,
    },
    {
      "id": "tomato_rice",
      "name": "Tomato Rice",
      "aliases": [],
      "per100g": {"kcal": 140, "protein_g": 2.5, "carbs_g": 24.0, "fat_g": 4.0},
      "defaultPortionG": 150,
      "category": "RICE MEALS",
      "estimated": true,
    },
    {
      "id": "coconut_rice",
      "name": "Coconut Rice",
      "aliases": ["kobbari annam"],
      "per100g": {"kcal": 180, "protein_g": 2.5, "carbs_g": 22.0, "fat_g": 9.0},
      "defaultPortionG": 150,
      "category": "RICE MEALS",
      "estimated": true,
    },
    {
      "id": "biryani",
      "name": "Chicken Biryani",
      "aliases": [
        "hyderabadi dum biryani",
        "biryani",
        "dum biryani",
        "kodi biryani",
      ],
      "per100g": {"kcal": 180, "protein_g": 8.0, "carbs_g": 24.0, "fat_g": 7.0},
      "defaultPortionG": 300,
      "category": "RICE MEALS",
      "estimated": true,
    },
    {
      "id": "veg_biryani",
      "name": "Veg Biryani",
      "aliases": ["vegetable biryani", "veg dum biryani"],
      "per100g": {"kcal": 160, "protein_g": 4.0, "carbs_g": 26.0, "fat_g": 6.0},
      "defaultPortionG": 300,
      "category": "RICE MEALS",
      "estimated": true,
    },
    {
      "id": "pulao",
      "name": "Veg Pulao",
      "aliases": ["pulao", "pilaf", "veg pulao"],
      "per100g": {"kcal": 140, "protein_g": 3.5, "carbs_g": 25.0, "fat_g": 4.0},
      "defaultPortionG": 250,
      "category": "RICE MEALS",
      "estimated": true,
    },

    // CURRIES & GRAVIES
    {
      "id": "pappu",
      "name": "Pappu",
      "aliases": ["dal", "lentils", "yellow dal"],
      "per100g": {"kcal": 110, "protein_g": 5.0, "carbs_g": 14.0, "fat_g": 4.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "tomato_pappu",
      "name": "Tomato Pappu",
      "aliases": ["tomato dal"],
      "per100g": {"kcal": 105, "protein_g": 4.5, "carbs_g": 13.0, "fat_g": 4.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "dosakaya_pappu",
      "name": "Dosakaya Pappu",
      "aliases": ["dosakaya dal", "cucumber dal"],
      "per100g": {"kcal": 105, "protein_g": 4.5, "carbs_g": 13.0, "fat_g": 4.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "sambar",
      "name": "Sambar",
      "aliases": ["sambhar"],
      "per100g": {"kcal": 60, "protein_g": 2.5, "carbs_g": 8.0, "fat_g": 2.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "rasam",
      "name": "Rasam",
      "aliases": ["charu", "soup"],
      "per100g": {"kcal": 40, "protein_g": 1.0, "carbs_g": 6.0, "fat_g": 1.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "chicken_curry",
      "name": "Chicken Curry",
      "aliases": ["kodi kura", "chicken gravy"],
      "per100g": {
        "kcal": 160,
        "protein_g": 14.0,
        "carbs_g": 5.0,
        "fat_g": 10.0,
      },
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "mutton_curry",
      "name": "Mutton Curry",
      "aliases": ["mamsam kura"],
      "per100g": {
        "kcal": 200,
        "protein_g": 16.0,
        "carbs_g": 6.0,
        "fat_g": 13.0,
      },
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "fish_curry",
      "name": "Fish Curry",
      "aliases": ["chepala pulusu"],
      "per100g": {"kcal": 140, "protein_g": 15.0, "carbs_g": 4.0, "fat_g": 7.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "egg_curry",
      "name": "Egg Curry",
      "aliases": ["guddu pulusu", "anda curry"],
      "per100g": {"kcal": 150, "protein_g": 9.0, "carbs_g": 6.0, "fat_g": 10.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "gutti_vankaya",
      "name": "Stuffed Brinjal",
      "aliases": ["gutti vankaya", "bagara baingan"],
      "per100g": {
        "kcal": 130,
        "protein_g": 2.0,
        "carbs_g": 10.0,
        "fat_g": 10.0,
      },
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "dondakaya",
      "name": "Dondakaya Fry",
      "aliases": ["ivy gourd fry"],
      "per100g": {
        "kcal": 180,
        "protein_g": 2.0,
        "carbs_g": 12.0,
        "fat_g": 14.0,
      },
      "defaultPortionG": 100,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "bendakaya",
      "name": "Bendakaya Fry",
      "aliases": ["okra fry", "bhindi fry"],
      "per100g": {
        "kcal": 150,
        "protein_g": 2.0,
        "carbs_g": 10.0,
        "fat_g": 12.0,
      },
      "defaultPortionG": 100,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "beerakaya",
      "name": "Beerakaya Curry",
      "aliases": ["ridge gourd curry"],
      "per100g": {"kcal": 90, "protein_g": 1.5, "carbs_g": 7.0, "fat_g": 6.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "sorakaya",
      "name": "Sorakaya Curry",
      "aliases": ["bottle gourd curry", "lauki"],
      "per100g": {"kcal": 70, "protein_g": 1.0, "carbs_g": 6.0, "fat_g": 5.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },
    {
      "id": "aloo_gobi",
      "name": "Aloo Gobi",
      "aliases": [],
      "per100g": {"kcal": 120, "protein_g": 2.5, "carbs_g": 14.0, "fat_g": 7.0},
      "defaultPortionG": 150,
      "category": "CURRIES",
      "estimated": true,
    },

    // BREAKFAST/TIFFIN
    {
      "id": "idli",
      "name": "Idli",
      "aliases": [],
      "per100g": {"kcal": 150, "protein_g": 5.0, "carbs_g": 32.0, "fat_g": 0.5},
      "defaultPortionG": 100,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "dosa",
      "name": "Dosa",
      "aliases": ["plain dosa"],
      "per100g": {"kcal": 200, "protein_g": 4.0, "carbs_g": 30.0, "fat_g": 7.0},
      "defaultPortionG": 100,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "masala_dosa",
      "name": "Masala Dosa",
      "aliases": [],
      "per100g": {"kcal": 180, "protein_g": 4.0, "carbs_g": 28.0, "fat_g": 8.0},
      "defaultPortionG": 150,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "pesarattu",
      "name": "Pesarattu",
      "aliases": ["moong dal dosa"],
      "per100g": {"kcal": 190, "protein_g": 7.0, "carbs_g": 25.0, "fat_g": 7.0},
      "defaultPortionG": 120,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "upma",
      "name": "Upma",
      "aliases": [],
      "per100g": {"kcal": 150, "protein_g": 3.0, "carbs_g": 22.0, "fat_g": 5.0},
      "defaultPortionG": 150,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "poha",
      "name": "Poha",
      "aliases": ["atukulu", "aval"],
      "per100g": {"kcal": 160, "protein_g": 3.0, "carbs_g": 28.0, "fat_g": 4.0},
      "defaultPortionG": 150,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "puri",
      "name": "Puri",
      "aliases": ["poori"],
      "per100g": {
        "kcal": 320,
        "protein_g": 6.0,
        "carbs_g": 40.0,
        "fat_g": 15.0,
      },
      "defaultPortionG": 80,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "vada",
      "name": "Vada",
      "aliases": ["garelu", "medu vada"],
      "per100g": {
        "kcal": 280,
        "protein_g": 8.0,
        "carbs_g": 28.0,
        "fat_g": 15.0,
      },
      "defaultPortionG": 100,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "uttapam",
      "name": "Uttapam",
      "aliases": ["uthappam"],
      "per100g": {"kcal": 170, "protein_g": 4.5, "carbs_g": 28.0, "fat_g": 5.0},
      "defaultPortionG": 150,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "ragi_mudde",
      "name": "Ragi Mudde",
      "aliases": ["ragi sangati"],
      "per100g": {"kcal": 140, "protein_g": 3.0, "carbs_g": 30.0, "fat_g": 0.5},
      "defaultPortionG": 200,
      "category": "TIFFIN",
      "estimated": true,
    },
    {
      "id": "jowar_roti",
      "name": "Jowar Roti",
      "aliases": ["jonnna rotte"],
      "per100g": {"kcal": 150, "protein_g": 4.0, "carbs_g": 32.0, "fat_g": 1.0},
      "defaultPortionG": 80,
      "category": "TIFFIN",
      "estimated": true,
    },

    // PICKLES & SIDES
    {
      "id": "avakaya",
      "name": "Avakaya",
      "aliases": ["mango pickle"],
      "per100g": {
        "kcal": 350,
        "protein_g": 2.0,
        "carbs_g": 15.0,
        "fat_g": 30.0,
      },
      "defaultPortionG": 20,
      "category": "PICKLES",
      "estimated": true,
    },
    {
      "id": "gongura_pachadi",
      "name": "Gongura Pachadi",
      "aliases": ["gongura pickle"],
      "per100g": {
        "kcal": 280,
        "protein_g": 3.0,
        "carbs_g": 12.0,
        "fat_g": 25.0,
      },
      "defaultPortionG": 20,
      "category": "PICKLES",
      "estimated": true,
    },
    {
      "id": "tomato_pachadi",
      "name": "Tomato Pachadi",
      "aliases": ["tomato chutney"],
      "per100g": {"kcal": 120, "protein_g": 2.0, "carbs_g": 10.0, "fat_g": 8.0},
      "defaultPortionG": 30,
      "category": "CHUTNEY",
      "estimated": true,
    },
    {
      "id": "peanut_chutney",
      "name": "Peanut Chutney",
      "aliases": ["palli chutney"],
      "per100g": {
        "kcal": 280,
        "protein_g": 8.0,
        "carbs_g": 12.0,
        "fat_g": 22.0,
      },
      "defaultPortionG": 30,
      "category": "CHUTNEY",
      "estimated": true,
    },
    {
      "id": "coconut_chutney",
      "name": "Coconut Chutney",
      "aliases": ["kobbari chutney"],
      "per100g": {"kcal": 250, "protein_g": 3.0, "carbs_g": 8.0, "fat_g": 24.0},
      "defaultPortionG": 30,
      "category": "CHUTNEY",
      "estimated": true,
    },
    {
      "id": "onion_chutney",
      "name": "Onion Chutney",
      "aliases": ["ullipaya pachadi"],
      "per100g": {"kcal": 150, "protein_g": 2.0, "carbs_g": 15.0, "fat_g": 9.0},
      "defaultPortionG": 30,
      "category": "CHUTNEY",
      "estimated": true,
    },
    {
      "id": "nuvvula_podi",
      "name": "Nuvvula Podi",
      "aliases": ["sesame powder"],
      "per100g": {
        "kcal": 500,
        "protein_g": 15.0,
        "carbs_g": 20.0,
        "fat_g": 40.0,
      },
      "defaultPortionG": 10,
      "category": "SIDES",
      "estimated": true,
    },
    {
      "id": "karam_podi",
      "name": "Karam Podi",
      "aliases": ["spice powder"],
      "per100g": {
        "kcal": 400,
        "protein_g": 12.0,
        "carbs_g": 50.0,
        "fat_g": 15.0,
      },
      "defaultPortionG": 10,
      "category": "SIDES",
      "estimated": true,
    },

    // SNACKS
    {
      "id": "mirchi_bajji",
      "name": "Mirchi Bajji",
      "aliases": ["mirapakaya bajji"],
      "per100g": {
        "kcal": 250,
        "protein_g": 5.0,
        "carbs_g": 25.0,
        "fat_g": 15.0,
      },
      "defaultPortionG": 100,
      "category": "SNACKS",
      "estimated": true,
    },
    {
      "id": "punugulu",
      "name": "Punugulu",
      "aliases": [],
      "per100g": {
        "kcal": 300,
        "protein_g": 5.0,
        "carbs_g": 40.0,
        "fat_g": 15.0,
      },
      "defaultPortionG": 100,
      "category": "SNACKS",
      "estimated": true,
    },
    {
      "id": "bonda",
      "name": "Bonda",
      "aliases": ["mysore bonda", "aloo bonda"],
      "per100g": {
        "kcal": 320,
        "protein_g": 6.0,
        "carbs_g": 35.0,
        "fat_g": 18.0,
      },
      "defaultPortionG": 100,
      "category": "SNACKS",
      "estimated": true,
    },
    {
      "id": "samosa",
      "name": "Samosa",
      "aliases": [],
      "per100g": {
        "kcal": 260,
        "protein_g": 4.0,
        "carbs_g": 28.0,
        "fat_g": 14.0,
      },
      "defaultPortionG": 100,
      "category": "SNACKS",
      "estimated": true,
    },
    {
      "id": "murukku",
      "name": "Murukku",
      "aliases": ["janthikalu", "chakli"],
      "per100g": {
        "kcal": 450,
        "protein_g": 8.0,
        "carbs_g": 55.0,
        "fat_g": 22.0,
      },
      "defaultPortionG": 50,
      "category": "SNACKS",
      "estimated": true,
    },
    {
      "id": "mixture",
      "name": "Mixture",
      "aliases": ["bombay mixture"],
      "per100g": {
        "kcal": 500,
        "protein_g": 10.0,
        "carbs_g": 45.0,
        "fat_g": 30.0,
      },
      "defaultPortionG": 50,
      "category": "SNACKS",
      "estimated": true,
    },

    // SWEETS
    {
      "id": "payasam",
      "name": "Payasam",
      "aliases": ["kheer"],
      "per100g": {"kcal": 150, "protein_g": 3.0, "carbs_g": 25.0, "fat_g": 4.0},
      "defaultPortionG": 150,
      "category": "SWEETS",
      "estimated": true,
    },
    {
      "id": "gulab_jamun",
      "name": "Gulab Jamun",
      "aliases": [],
      "per100g": {"kcal": 300, "protein_g": 4.0, "carbs_g": 55.0, "fat_g": 8.0},
      "defaultPortionG": 100,
      "category": "SWEETS",
      "estimated": true,
    },
    {
      "id": "laddu",
      "name": "Laddu",
      "aliases": ["laddoo", "boondi laddu"],
      "per100g": {
        "kcal": 450,
        "protein_g": 5.0,
        "carbs_g": 60.0,
        "fat_g": 20.0,
      },
      "defaultPortionG": 50,
      "category": "SWEETS",
      "estimated": true,
    },
    {
      "id": "jalebi",
      "name": "Jalebi",
      "aliases": [],
      "per100g": {"kcal": 350, "protein_g": 2.0, "carbs_g": 70.0, "fat_g": 5.0},
      "defaultPortionG": 50,
      "category": "SWEETS",
      "estimated": true,
    },
    {
      "id": "pootharekulu",
      "name": "Pootharekulu",
      "aliases": ["paper sweet"],
      "per100g": {
        "kcal": 400,
        "protein_g": 3.0,
        "carbs_g": 75.0,
        "fat_g": 10.0,
      },
      "defaultPortionG": 30,
      "category": "SWEETS",
      "estimated": true,
    },

    // NON-VEG
    {
      "id": "chicken_fry",
      "name": "Chicken Fry",
      "aliases": ["kodi vepudu"],
      "per100g": {
        "kcal": 250,
        "protein_g": 20.0,
        "carbs_g": 5.0,
        "fat_g": 16.0,
      },
      "defaultPortionG": 100,
      "category": "NON-VEG",
      "estimated": true,
    },
    {
      "id": "fish_fry",
      "name": "Fish Fry",
      "aliases": ["chepala vepudu"],
      "per100g": {
        "kcal": 220,
        "protein_g": 18.0,
        "carbs_g": 4.0,
        "fat_g": 14.0,
      },
      "defaultPortionG": 100,
      "category": "NON-VEG",
      "estimated": true,
    },
    {
      "id": "prawn_curry",
      "name": "Prawn Curry",
      "aliases": ["royyala kura", "shrimp curry"],
      "per100g": {"kcal": 150, "protein_g": 18.0, "carbs_g": 4.0, "fat_g": 7.0},
      "defaultPortionG": 150,
      "category": "NON-VEG",
      "estimated": true,
    },
    {
      "id": "keema",
      "name": "Keema",
      "aliases": ["minced meat curry"],
      "per100g": {
        "kcal": 220,
        "protein_g": 18.0,
        "carbs_g": 5.0,
        "fat_g": 14.0,
      },
      "defaultPortionG": 150,
      "category": "NON-VEG",
      "estimated": true,
    },
    {
      "id": "liver_fry",
      "name": "Liver Fry",
      "aliases": [],
      "per100g": {
        "kcal": 210,
        "protein_g": 25.0,
        "carbs_g": 5.0,
        "fat_g": 10.0,
      },
      "defaultPortionG": 100,
      "category": "NON-VEG",
      "estimated": true,
    },
    {
      "id": "egg_bhurji",
      "name": "Egg Bhurji",
      "aliases": ["kodi guddu porutu", "scrambled egg"],
      "per100g": {
        "kcal": 180,
        "protein_g": 12.0,
        "carbs_g": 4.0,
        "fat_g": 13.0,
      },
      "defaultPortionG": 100,
      "category": "NON-VEG",
      "estimated": true,
    },

    // ROTI/BREAD
    {
      "id": "chapati",
      "name": "Chapati",
      "aliases": ["roti", "phulka", "pulka"],
      "per100g": {
        "kcal": 300,
        "protein_g": 10.0,
        "carbs_g": 50.0,
        "fat_g": 5.0,
      },
      "defaultPortionG": 50,
      "category": "ROTI",
      "estimated": true,
    },
    {
      "id": "paratha",
      "name": "Paratha",
      "aliases": ["parotta"],
      "per100g": {
        "kcal": 330,
        "protein_g": 7.0,
        "carbs_g": 45.0,
        "fat_g": 12.0,
      },
      "defaultPortionG": 70,
      "category": "ROTI",
      "estimated": true,
    },
    {
      "id": "naan",
      "name": "Naan",
      "aliases": ["plain naan"],
      "per100g": {"kcal": 280, "protein_g": 8.0, "carbs_g": 48.0, "fat_g": 5.0},
      "defaultPortionG": 70,
      "category": "ROTI",
      "estimated": true,
    },
    {
      "id": "roti_ghee",
      "name": "Roti with Ghee",
      "aliases": ["ghee chapati"],
      "per100g": {
        "kcal": 350,
        "protein_g": 9.0,
        "carbs_g": 45.0,
        "fat_g": 12.0,
      },
      "defaultPortionG": 50,
      "category": "ROTI",
      "estimated": true,
    },

    // TANDOOR
    {
      "id": "tandoori_chicken",
      "name": "Tandoori Chicken",
      "aliases": [],
      "per100g": {"kcal": 170, "protein_g": 22.0, "carbs_g": 2.0, "fat_g": 8.0},
      "defaultPortionG": 200,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "chicken_tikka",
      "name": "Chicken Tikka",
      "aliases": [],
      "per100g": {"kcal": 160, "protein_g": 20.0, "carbs_g": 3.0, "fat_g": 7.0},
      "defaultPortionG": 150,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "paneer_tikka",
      "name": "Paneer Tikka",
      "aliases": [],
      "per100g": {
        "kcal": 250,
        "protein_g": 15.0,
        "carbs_g": 6.0,
        "fat_g": 18.0,
      },
      "defaultPortionG": 150,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "seekh_kebab",
      "name": "Seekh Kebab",
      "aliases": [],
      "per100g": {
        "kcal": 220,
        "protein_g": 18.0,
        "carbs_g": 4.0,
        "fat_g": 14.0,
      },
      "defaultPortionG": 150,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "tandoori_roti",
      "name": "Tandoori Roti",
      "aliases": [],
      "per100g": {"kcal": 260, "protein_g": 9.0, "carbs_g": 52.0, "fat_g": 2.0},
      "defaultPortionG": 60,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "butter_naan",
      "name": "Butter Naan",
      "aliases": [],
      "per100g": {
        "kcal": 320,
        "protein_g": 7.0,
        "carbs_g": 48.0,
        "fat_g": 10.0,
      },
      "defaultPortionG": 70,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "garlic_naan",
      "name": "Garlic Naan",
      "aliases": [],
      "per100g": {
        "kcal": 330,
        "protein_g": 7.0,
        "carbs_g": 49.0,
        "fat_g": 11.0,
      },
      "defaultPortionG": 70,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "kulcha",
      "name": "Kulcha",
      "aliases": [],
      "per100g": {"kcal": 290, "protein_g": 8.0, "carbs_g": 50.0, "fat_g": 6.0},
      "defaultPortionG": 70,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "tandoori_prawns",
      "name": "Tandoori Prawns",
      "aliases": [],
      "per100g": {"kcal": 130, "protein_g": 20.0, "carbs_g": 2.0, "fat_g": 4.0},
      "defaultPortionG": 150,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "reshmi_kebab",
      "name": "Reshmi Kebab",
      "aliases": [],
      "per100g": {"kcal": 180, "protein_g": 19.0, "carbs_g": 4.0, "fat_g": 9.0},
      "defaultPortionG": 150,
      "category": "TANDOOR",
      "estimated": true,
    },
    {
      "id": "malai_tikka",
      "name": "Malai Tikka",
      "aliases": [],
      "per100g": {
        "kcal": 210,
        "protein_g": 18.0,
        "carbs_g": 3.0,
        "fat_g": 14.0,
      },
      "defaultPortionG": 150,
      "category": "TANDOOR",
      "estimated": true,
    },

    // SALADS
    {
      "id": "caesar_salad",
      "name": "Caesar Salad",
      "aliases": [],
      "per100g": {"kcal": 180, "protein_g": 6.0, "carbs_g": 9.0, "fat_g": 13.0},
      "defaultPortionG": 200,
      "category": "SALADS",
      "estimated": true,
    },
    {
      "id": "greek_salad",
      "name": "Greek Salad",
      "aliases": [],
      "per100g": {"kcal": 100, "protein_g": 3.0, "carbs_g": 7.0, "fat_g": 7.0},
      "defaultPortionG": 200,
      "category": "SALADS",
      "estimated": true,
    },
    {
      "id": "garden_salad",
      "name": "Garden Salad",
      "aliases": ["mixed salad", "green salad"],
      "per100g": {"kcal": 30, "protein_g": 1.0, "carbs_g": 6.0, "fat_g": 0.5},
      "defaultPortionG": 200,
      "category": "SALADS",
      "estimated": true,
    },
    {
      "id": "paneer_salad",
      "name": "Paneer Salad",
      "aliases": ["paneer salad bowl"],
      "per100g": {"kcal": 140, "protein_g": 8.0, "carbs_g": 6.0, "fat_g": 9.0},
      "defaultPortionG": 250,
      "category": "SALADS",
      "estimated": true,
    },
    {
      "id": "chicken_salad",
      "name": "Chicken Salad",
      "aliases": ["chicken salad bowl"],
      "per100g": {"kcal": 130, "protein_g": 12.0, "carbs_g": 5.0, "fat_g": 7.0},
      "defaultPortionG": 250,
      "category": "SALADS",
      "estimated": true,
    },
    {
      "id": "quinoa_salad",
      "name": "Quinoa Salad",
      "aliases": [],
      "per100g": {"kcal": 120, "protein_g": 4.0, "carbs_g": 18.0, "fat_g": 3.5},
      "defaultPortionG": 200,
      "category": "SALADS",
      "estimated": true,
    },
    {
      "id": "sprout_salad",
      "name": "Sprout Salad",
      "aliases": ["moong sprouts"],
      "per100g": {"kcal": 100, "protein_g": 8.0, "carbs_g": 16.0, "fat_g": 1.0},
      "defaultPortionG": 150,
      "category": "SALADS",
      "estimated": true,
    },
    {
      "id": "fruit_salad",
      "name": "Fruit Salad",
      "aliases": ["mixed fruit bowl"],
      "per100g": {"kcal": 50, "protein_g": 0.5, "carbs_g": 13.0, "fat_g": 0.2},
      "defaultPortionG": 200,
      "category": "SALADS",
      "estimated": true,
    },
    {
      "id": "coleslaw",
      "name": "Coleslaw",
      "aliases": [],
      "per100g": {
        "kcal": 150,
        "protein_g": 1.0,
        "carbs_g": 10.0,
        "fat_g": 12.0,
      },
      "defaultPortionG": 100,
      "category": "SALADS",
      "estimated": true,
    },

    // RICE BOWLS
    {
      "id": "burrito_bowl",
      "name": "Burrito Bowl",
      "aliases": [],
      "per100g": {"kcal": 150, "protein_g": 6.0, "carbs_g": 18.0, "fat_g": 6.0},
      "defaultPortionG": 350,
      "category": "RICE BOWLS",
      "estimated": true,
    },
    {
      "id": "poke_bowl",
      "name": "Poke Bowl",
      "aliases": [],
      "per100g": {"kcal": 140, "protein_g": 8.0, "carbs_g": 16.0, "fat_g": 4.5},
      "defaultPortionG": 350,
      "category": "RICE BOWLS",
      "estimated": true,
    },
    {
      "id": "teriyaki_chicken_bowl",
      "name": "Teriyaki Chicken Bowl",
      "aliases": [],
      "per100g": {"kcal": 160, "protein_g": 9.0, "carbs_g": 22.0, "fat_g": 4.0},
      "defaultPortionG": 350,
      "category": "RICE BOWLS",
      "estimated": true,
    },
    {
      "id": "paneer_tikka_bowl",
      "name": "Paneer Tikka Rice Bowl",
      "aliases": [],
      "per100g": {"kcal": 170, "protein_g": 6.0, "carbs_g": 20.0, "fat_g": 7.0},
      "defaultPortionG": 350,
      "category": "RICE BOWLS",
      "estimated": true,
    },
    {
      "id": "mexican_rice_bowl",
      "name": "Mexican Rice Bowl",
      "aliases": [],
      "per100g": {"kcal": 150, "protein_g": 5.0, "carbs_g": 22.0, "fat_g": 5.0},
      "defaultPortionG": 350,
      "category": "RICE BOWLS",
      "estimated": true,
    },
    {
      "id": "buddha_bowl",
      "name": "Buddha Bowl",
      "aliases": [],
      "per100g": {"kcal": 130, "protein_g": 5.0, "carbs_g": 15.0, "fat_g": 6.0},
      "defaultPortionG": 350,
      "category": "RICE BOWLS",
      "estimated": true,
    },
    {
      "id": "grain_bowl",
      "name": "Grain Bowl",
      "aliases": [],
      "per100g": {"kcal": 140, "protein_g": 4.5, "carbs_g": 20.0, "fat_g": 5.0},
      "defaultPortionG": 350,
      "category": "RICE BOWLS",
      "estimated": true,
    },

    // NORTH INDIAN RESTAURANT
    {
      "id": "butter_chicken",
      "name": "Butter Chicken",
      "aliases": ["murgh makhani"],
      "per100g": {
        "kcal": 220,
        "protein_g": 14.0,
        "carbs_g": 6.0,
        "fat_g": 15.0,
      },
      "defaultPortionG": 150,
      "category": "NORTH INDIAN",
      "estimated": true,
    },
    {
      "id": "dal_makhani",
      "name": "Dal Makhani",
      "aliases": [],
      "per100g": {"kcal": 180, "protein_g": 6.0, "carbs_g": 18.0, "fat_g": 9.0},
      "defaultPortionG": 150,
      "category": "NORTH INDIAN",
      "estimated": true,
    },
    {
      "id": "palak_paneer",
      "name": "Palak Paneer",
      "aliases": [],
      "per100g": {"kcal": 190, "protein_g": 8.0, "carbs_g": 7.0, "fat_g": 14.0},
      "defaultPortionG": 150,
      "category": "NORTH INDIAN",
      "estimated": true,
    },
    {
      "id": "kadai_paneer",
      "name": "Kadai Paneer",
      "aliases": [],
      "per100g": {"kcal": 210, "protein_g": 9.0, "carbs_g": 8.0, "fat_g": 16.0},
      "defaultPortionG": 150,
      "category": "NORTH INDIAN",
      "estimated": true,
    },
    {
      "id": "chole_bhature",
      "name": "Chole Bhature",
      "aliases": ["chana bhatura"],
      "per100g": {
        "kcal": 300,
        "protein_g": 6.0,
        "carbs_g": 35.0,
        "fat_g": 15.0,
      },
      "defaultPortionG": 250,
      "category": "NORTH INDIAN",
      "estimated": true,
    },
    {
      "id": "rajma_chawal",
      "name": "Rajma Chawal",
      "aliases": [],
      "per100g": {"kcal": 150, "protein_g": 5.0, "carbs_g": 25.0, "fat_g": 3.0},
      "defaultPortionG": 300,
      "category": "NORTH INDIAN",
      "estimated": true,
    },
    {
      "id": "shahi_paneer",
      "name": "Shahi Paneer",
      "aliases": [],
      "per100g": {
        "kcal": 240,
        "protein_g": 8.0,
        "carbs_g": 10.0,
        "fat_g": 19.0,
      },
      "defaultPortionG": 150,
      "category": "NORTH INDIAN",
      "estimated": true,
    },
    {
      "id": "malai_kofta",
      "name": "Malai Kofta",
      "aliases": [],
      "per100g": {
        "kcal": 260,
        "protein_g": 6.0,
        "carbs_g": 18.0,
        "fat_g": 18.0,
      },
      "defaultPortionG": 150,
      "category": "NORTH INDIAN",
      "estimated": true,
    },
    {
      "id": "paneer_butter_masala",
      "name": "Paneer Butter Masala",
      "aliases": ["paneer curry", "butter paneer"],
      "per100g": {
        "kcal": 260,
        "protein_g": 12.0,
        "carbs_g": 12.0,
        "fat_g": 18.0,
      },
      "defaultPortionG": 150,
      "category": "NORTH INDIAN",
      "estimated": true,
    },

    // CAFÉ & WESTERN
    {
      "id": "sandwich",
      "name": "Sandwich",
      "aliases": ["veg sandwich"],
      "per100g": {"kcal": 220, "protein_g": 8.0, "carbs_g": 28.0, "fat_g": 8.0},
      "defaultPortionG": 150,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "wrap",
      "name": "Wrap",
      "aliases": ["roll", "frankie"],
      "per100g": {
        "kcal": 240,
        "protein_g": 9.0,
        "carbs_g": 30.0,
        "fat_g": 10.0,
      },
      "defaultPortionG": 200,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "burger",
      "name": "Burger",
      "aliases": ["hamburger", "veg burger"],
      "per100g": {
        "kcal": 280,
        "protein_g": 10.0,
        "carbs_g": 30.0,
        "fat_g": 12.0,
      },
      "defaultPortionG": 200,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "pizza",
      "name": "Pizza",
      "aliases": [],
      "per100g": {
        "kcal": 260,
        "protein_g": 11.0,
        "carbs_g": 33.0,
        "fat_g": 10.0,
      },
      "defaultPortionG": 250,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "pasta",
      "name": "Pasta",
      "aliases": ["penne pasta"],
      "per100g": {"kcal": 160, "protein_g": 5.0, "carbs_g": 30.0, "fat_g": 3.0},
      "defaultPortionG": 250,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "grilled_chicken",
      "name": "Grilled Chicken",
      "aliases": [],
      "per100g": {"kcal": 150, "protein_g": 25.0, "carbs_g": 0.0, "fat_g": 5.0},
      "defaultPortionG": 150,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "french_fries",
      "name": "French Fries",
      "aliases": ["fries"],
      "per100g": {
        "kcal": 310,
        "protein_g": 3.5,
        "carbs_g": 40.0,
        "fat_g": 15.0,
      },
      "defaultPortionG": 120,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "smoothie_bowl",
      "name": "Smoothie Bowl",
      "aliases": [],
      "per100g": {"kcal": 90, "protein_g": 2.0, "carbs_g": 18.0, "fat_g": 1.5},
      "defaultPortionG": 300,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "acai_bowl",
      "name": "Açaí Bowl",
      "aliases": ["acai bowl"],
      "per100g": {"kcal": 100, "protein_g": 2.0, "carbs_g": 20.0, "fat_g": 2.0},
      "defaultPortionG": 300,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "avocado_toast",
      "name": "Avocado Toast",
      "aliases": [],
      "per100g": {
        "kcal": 220,
        "protein_g": 5.0,
        "carbs_g": 25.0,
        "fat_g": 12.0,
      },
      "defaultPortionG": 150,
      "category": "WESTERN",
      "estimated": true,
    },
    {
      "id": "omelette",
      "name": "Omelette",
      "aliases": ["omelet"],
      "per100g": {
        "kcal": 150,
        "protein_g": 11.0,
        "carbs_g": 1.0,
        "fat_g": 11.0,
      },
      "defaultPortionG": 120,
      "category": "WESTERN",
      "estimated": true,
    },

    // DRINKS
    {
      "id": "chai",
      "name": "Chai",
      "aliases": ["tea", "milk tea"],
      "per100g": {"kcal": 40, "protein_g": 1.0, "carbs_g": 7.0, "fat_g": 1.0},
      "defaultPortionG": 150,
      "category": "DRINKS",
      "estimated": true,
    },
    {
      "id": "coffee",
      "name": "Coffee",
      "aliases": ["filter coffee", "milk coffee"],
      "per100g": {"kcal": 45, "protein_g": 1.2, "carbs_g": 8.0, "fat_g": 1.0},
      "defaultPortionG": 150,
      "category": "DRINKS",
      "estimated": true,
    },
    {
      "id": "lassi",
      "name": "Lassi",
      "aliases": ["sweet lassi"],
      "per100g": {"kcal": 80, "protein_g": 2.5, "carbs_g": 12.0, "fat_g": 2.5},
      "defaultPortionG": 250,
      "category": "DRINKS",
      "estimated": true,
    },
    {
      "id": "majjiga",
      "name": "Majjiga",
      "aliases": ["buttermilk", "chaas"],
      "per100g": {"kcal": 20, "protein_g": 1.0, "carbs_g": 2.0, "fat_g": 1.0},
      "defaultPortionG": 250,
      "category": "DRINKS",
      "estimated": true,
    },
    {
      "id": "fresh_juice",
      "name": "Fresh Juice",
      "aliases": ["orange juice", "apple juice"],
      "per100g": {"kcal": 45, "protein_g": 0.5, "carbs_g": 11.0, "fat_g": 0.1},
      "defaultPortionG": 250,
      "category": "DRINKS",
      "estimated": true,
    },
    {
      "id": "smoothie",
      "name": "Smoothie",
      "aliases": ["fruit smoothie"],
      "per100g": {"kcal": 60, "protein_g": 1.5, "carbs_g": 12.0, "fat_g": 0.5},
      "defaultPortionG": 300,
      "category": "DRINKS",
      "estimated": true,
    },
    {
      "id": "milkshake",
      "name": "Milkshake",
      "aliases": [],
      "per100g": {"kcal": 100, "protein_g": 3.0, "carbs_g": 15.0, "fat_g": 3.0},
      "defaultPortionG": 300,
      "category": "DRINKS",
      "estimated": true,
    },
    {
      "id": "protein_shake",
      "name": "Protein Shake",
      "aliases": ["whey protein"],
      "per100g": {"kcal": 50, "protein_g": 8.0, "carbs_g": 3.0, "fat_g": 0.5},
      "defaultPortionG": 300,
      "category": "DRINKS",
      "estimated": true,
    },
  ];
  for (var item in table) {
    if (item.containsKey('per100g')) {
      item['is_per_100g'] = true;
      item['base_quantity_unit'] = 'g';
    } else {
      item['is_per_100g'] = false;
      item['base_quantity_unit'] = 'serving';
    }
  }

  print('Generating nutrition table with ${table.length} items...');
  File('assets/data/nutrition_table.json').writeAsStringSync(jsonEncode(table));
  print('Done!');
}
